cat include/Arena.h
cat include/Assets.h
cat include/Component.h
cat include/Entity.h
cat include/Game.h
cat include/System.h
cat include/Utils.h
cat src/Arena.c
cat src/Assets.c
cat src/Component.c
cat src/Entity.c
cat src/Game.c
cat src/System.c
cat src/Utils.c
cat src/main.c